/**
 * Seed data generator for Portal Premium
 * Creates realistic properties for PT and AO markets
 */

export const seedProperties = [
  // ─── PORTUGAL ───
  {
    title: 'Moradia de Luxo em Talatona',
    description: 'Propriedade de referência na Península do Porto. Arquitetura contemporânea com materiais nobres, jardim tropical privado e acesso direto ao campo de golfe. Isenção de IPU disponível para estrangeiros.',
    price: 2850000000,
    currency: 'AOA',
    address: 'Rua da Península, Lote 45',
    city: 'Luanda',
    country: 'AO',
    neighborhood: 'Talatona',
    latitude: -8.9167,
    longitude: 13.1833,
    typology: 'T5',
    bedrooms: 5,
    bathrooms: 6,
    sqm: 420,
    parking: 3,
    pool: true,
    garden: true,
    energyCertificate: 'A',
    walkScore: 62,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80', alt: 'Fachada principal', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80', alt: 'Sala de estar' },
    ]),
    tags: JSON.stringify(['Nova Construção', 'Península do Porto', 'Piscina']),
    propertyType: 'moradia-independente',
    condition: 'nova',
    hasVirtualTour: true,
    virtualTourUrl: 'https://my.matterport.com/show/?m=example1',
  },
  {
    title: 'Apartamento Panorâmico na Ilha do Cabo',
    description: 'Vistas deslumbrantes sobre a baía de Luanda. Acabamentos de luxo, cozinha equipada Gaggenau, varanda suspensa de 40m². Segurança 24h e sistema de estacionamento subterrâneo.',
    price: 1850000000,
    currency: 'AOA',
    address: 'Avenida Murtala Mohammed, Edifício Miramar Tower',
    city: 'Luanda',
    country: 'AO',
    neighborhood: 'Ilha do Cabo',
    latitude: -8.8167,
    longitude: 13.2333,
    typology: 'T4',
    bedrooms: 4,
    bathrooms: 4,
    sqm: 280,
    parking: 2,
    pool: true,
    garden: false,
    energyCertificate: 'A',
    walkScore: 78,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80', alt: 'Vista da varanda', isPrimary: true },
    ]),
    tags: JSON.stringify(['Vista Mar', 'Segurança 24h', 'Luxo']),
    propertyType: 'apartamento',
    condition: 'bom-estado',
  },
  {
    title: 'Palacete Renovado em Cascais',
    description: 'Exemplar único de arquitetura manuelina revitalizada. Pátio interior com jardim zen, piscina aquecida e adega climatizada. A 5 minutos a pé da marina. Certificação energética A+.',
    price: 450000000,
    currency: 'EUR',
    address: 'Rua do Visconde da Luz, 120',
    city: 'Cascais',
    country: 'PT',
    neighborhood: 'Centro Histórico',
    latitude: 38.697,
    longitude: -9.422,
    typology: 'T6',
    bedrooms: 6,
    bathrooms: 7,
    sqm: 580,
    parking: 4,
    pool: true,
    garden: true,
    energyCertificate: 'A+',
    walkScore: 91,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80', alt: 'Fachada histórica', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80', alt: 'Jardim interior' },
    ]),
    tags: JSON.stringify(['Património', 'A+', 'Marina']),
    propertyType: 'moradia-independente',
    condition: 'recuperado',
    hasVirtualTour: true,
    virtualTourUrl: 'https://my.matterport.com/show/?m=example2',
  },
  {
    title: 'Penthouse com Rooftop em Lisboa',
    description: 'Duplex no topo do edifício ICON. Rooftop privado de 120m², jacuzzi exterior, cozinha de verão. Vista 360° sobre o Tejo e Castelo de São Jorge.',
    price: 320000000,
    currency: 'EUR',
    address: 'Avenida da Liberdade, 245, Piso 15',
    city: 'Lisboa',
    country: 'PT',
    neighborhood: 'Avenidas Novas',
    latitude: 38.7223,
    longitude: -9.1453,
    typology: 'T4',
    bedrooms: 4,
    bathrooms: 5,
    sqm: 350,
    parking: 2,
    pool: false,
    garden: false,
    energyCertificate: 'A',
    walkScore: 96,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80', alt: 'Rooftop privado', isPrimary: true },
    ]),
    tags: JSON.stringify(['Rooftop', 'Vista Tejo', 'Duplex']),
    propertyType: 'penthouse',
    condition: 'nova',
  },
  {
    title: 'Loft Industrial no Porto',
    description: 'Conversão de armazém do século XIX em espaço contemporâneo. Tetos de 5m, janelas industriais originais, piso em microcimento. Zona das Artes, a 3 minutos da Casa da Música.',
    price: 98500000,
    currency: 'EUR',
    address: 'Rua de Miguel Bombarda, 45',
    city: 'Porto',
    country: 'PT',
    neighborhood: 'Cedofeita',
    latitude: 41.1485,
    longitude: -8.611,
    typology: 'T2',
    bedrooms: 2,
    bathrooms: 2,
    sqm: 145,
    parking: 1,
    pool: false,
    garden: false,
    energyCertificate: 'B',
    walkScore: 94,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&q=80', alt: 'Sala loft', isPrimary: true },
    ]),
    tags: JSON.stringify(['Loft', 'Design', 'Casa da Música']),
    propertyType: 'loft',
    condition: 'recuperado',
  },
  {
    title: 'Vila Premium em Miramar',
    description: 'Residência exclusiva em condomínio fechado de alta segurança. Piscina infinita, smart home integrada, gerador autónomo. Ideal para expatriados e diplomatas.',
    price: 4200000000,
    currency: 'AOA',
    address: 'Condomínio Miramar Premium, Via A1',
    city: 'Luanda',
    country: 'AO',
    neighborhood: 'Miramar',
    latitude: -8.8333,
    longitude: 13.25,
    typology: 'T5',
    bedrooms: 5,
    bathrooms: 6,
    sqm: 500,
    parking: 4,
    pool: true,
    garden: true,
    energyCertificate: 'A',
    walkScore: 45,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1605146768851-eda79da39897?w=800&q=80', alt: 'Piscina infinita', isPrimary: true },
    ]),
    tags: JSON.stringify(['Segurança 24h', 'Smart Home', 'Gerador']),
    propertyType: 'villa',
    condition: 'nova',
  },
  // ─── MAIS PROPRIEDADES PT ───
  {
    title: 'Apartamento T3 Renovado em Alfama',
    description: 'Apartamento tipico alfacinha completamente renovado com terraço com vista para o Tejo. Cozinha equipada, sala ampla, 2 casas de banho completas.',
    price: 42500000,
    currency: 'EUR',
    address: 'Beco do Carreiro, 12, 2º Esq',
    city: 'Lisboa',
    country: 'PT',
    neighborhood: 'Alfama',
    latitude: 38.712,
    longitude: -9.13,
    typology: 'T3',
    bedrooms: 3,
    bathrooms: 2,
    sqm: 95,
    parking: 0,
    pool: false,
    garden: false,
    energyCertificate: 'C',
    walkScore: 92,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80', alt: 'Terraço vista Tejo', isPrimary: true },
    ]),
    tags: JSON.stringify(['Vista Tejo', 'Terraço', 'Histórico']),
    propertyType: 'apartamento',
    condition: 'recuperado',
  },
  {
    title: 'Moradia Geminada T4 em Matosinhos',
    description: 'Moradia em banda a 500m da praia. Jardim privado, garagem para 2 carros, sótão convertido em escritório. Zona familiar com escolas e comércio.',
    price: 67500000,
    currency: 'EUR',
    address: 'Rua de Brito Capelo, 340',
    city: 'Matosinhos',
    country: 'PT',
    neighborhood: 'Matosinhos Sul',
    latitude: 41.174,
    longitude: -8.69,
    typology: 'T4',
    bedrooms: 4,
    bathrooms: 3,
    sqm: 210,
    parking: 2,
    pool: false,
    garden: true,
    energyCertificate: 'B',
    walkScore: 78,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80', alt: 'Fachada moradia', isPrimary: true },
    ]),
    tags: JSON.stringify(['Praia', 'Família', 'Jardim']),
    propertyType: 'moradia-geminada',
    condition: 'bom-estado',
  },
  {
    title: 'Apartamento T1+1 na Expo',
    description: 'Apartamento moderno em zona privilegiada do Parque das Nações. Varanda com 15m², arrecadação, estacionamento na cave. Perto do Oceanário e Vasco da Gama.',
    price: 38500000,
    currency: 'EUR',
    address: 'Avenida D. João II, Lote 3.2.1',
    city: 'Lisboa',
    country: 'PT',
    neighborhood: 'Parque das Nações',
    latitude: 38.767,
    longitude: -9.093,
    typology: 'T1+1',
    bedrooms: 1,
    bathrooms: 1,
    sqm: 75,
    parking: 1,
    pool: false,
    garden: false,
    energyCertificate: 'A',
    walkScore: 85,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80', alt: 'Sala moderna', isPrimary: true },
    ]),
    tags: JSON.stringify(['Expo', 'Moderno', 'Rio']),
    propertyType: 'apartamento',
    condition: 'bom-estado',
  },
  {
    title: 'Quinta T7 no Alentejo',
    description: 'Propriedade rural com 12 hectares, casa senhorial do século XVIII restaurada, anexos convertidos em suites, piscina natural, oliveiral e vinha.',
    price: 125000000,
    currency: 'EUR',
    address: 'Herdade da Saudade, Estrada Municipal 120',
    city: 'Évora',
    country: 'PT',
    neighborhood: 'Reguengos de Monsaraz',
    latitude: 38.425,
    longitude: -7.45,
    typology: 'T7',
    bedrooms: 7,
    bathrooms: 6,
    sqm: 650,
    parking: 6,
    pool: true,
    garden: true,
    energyCertificate: 'C',
    walkScore: 25,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80', alt: 'Quinta alentejana', isPrimary: true },
    ]),
    tags: JSON.stringify(['Turismo Rural', 'Hectares', 'Piscina Natural']),
    propertyType: 'quinta',
    condition: 'recuperado',
  },
  {
    title: 'Apartamento T2 em Arrendamento no Chiado',
    description: 'Apartamento totalmente mobilado e equipado no coração do Chiado. Edifício com elevador, ar condicionado, internet incluída. Disponível para arrendamento anual.',
    price: 185000,
    currency: 'EUR',
    address: 'Rua Garrett, 75, 3º Dir',
    city: 'Lisboa',
    country: 'PT',
    neighborhood: 'Chiado',
    latitude: 38.71,
    longitude: -9.14,
    typology: 'T2',
    bedrooms: 2,
    bathrooms: 1,
    sqm: 68,
    parking: 0,
    pool: false,
    garden: false,
    energyCertificate: 'D',
    walkScore: 99,
    listingType: 'rent',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80', alt: 'Sala mobilada', isPrimary: true },
    ]),
    tags: JSON.stringify(['Mobilado', 'Chiado', 'Anual']),
    propertyType: 'apartamento',
    condition: 'bom-estado',
  },
  {
    title: 'Moradia Térrea T3 em Lagos',
    description: 'Moradia térrea em condomínio fechado com piscina comunitária. Jardim privado, estacionamento, a 10 minutos da praia de Dona Ana.',
    price: 52000000,
    currency: 'EUR',
    address: 'Urbanização Vale da Lama, Lote 45',
    city: 'Lagos',
    country: 'PT',
    neighborhood: 'Porto de Mós',
    latitude: 37.095,
    longitude: -8.67,
    typology: 'T3',
    bedrooms: 3,
    bathrooms: 2,
    sqm: 145,
    parking: 1,
    pool: true,
    garden: true,
    energyCertificate: 'B',
    walkScore: 55,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80', alt: 'Jardim privado', isPrimary: true },
    ]),
    tags: JSON.stringify(['Algarve', 'Praia', 'Condomínio']),
    propertyType: 'moradia-terrea',
    condition: 'bom-estado',
  },
  // ─── MAIS PROPRIEDADES AO ───
  {
    title: 'Apartamento T2 em Benguela',
    description: 'Apartamento novo em empreendimento junto à baía de Benguela. Vista mar, acabamentos de qualidade, estacionamento e piscina no rooftop.',
    price: 780000000,
    currency: 'AOA',
    address: 'Avenida da Liberdade, Edifício Baía Azul',
    city: 'Benguela',
    country: 'AO',
    neighborhood: 'Baía Farta',
    latitude: -12.55,
    longitude: 13.4,
    typology: 'T2',
    bedrooms: 2,
    bathrooms: 2,
    sqm: 110,
    parking: 1,
    pool: true,
    garden: false,
    energyCertificate: 'A',
    walkScore: 70,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80', alt: 'Vista baía', isPrimary: true },
    ]),
    tags: JSON.stringify(['Vista Mar', 'Novo', 'Benguela']),
    propertyType: 'apartamento',
    condition: 'nova',
  },
  {
    title: 'Escritório Comercial em Luanda Sul',
    description: 'Escritório de 200m² em edifício corporativo de classe A. Recepção, 5 salas, sala de reuniões, kitchenette. Estacionamento para 8 viaturas.',
    price: 950000000,
    currency: 'AOA',
    address: 'Avenida Nicolau Gomes Spencer, Torres Infinity',
    city: 'Luanda',
    country: 'AO',
    neighborhood: 'Luanda Sul',
    latitude: -8.88,
    longitude: 13.2,
    typology: 'Escritório',
    bedrooms: 0,
    bathrooms: 3,
    sqm: 200,
    parking: 8,
    pool: false,
    garden: false,
    energyCertificate: 'A',
    walkScore: 60,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80', alt: 'Open space', isPrimary: true },
    ]),
    tags: JSON.stringify(['Corporativo', 'Classe A', 'Negócio']),
    propertyType: 'escritorio',
    condition: 'nova',
  },
  {
    title: 'Moradia T3 em Lubango',
    description: 'Moradia familiar com jardim amplo, vista para a Serra da Chela. Garagem para 2 carros, área de lazer com churrasqueira.',
    price: 420000000,
    currency: 'AOA',
    address: 'Rua da Missão, Bairro da Graça',
    city: 'Lubango',
    country: 'AO',
    neighborhood: 'Bairro da Graça',
    latitude: -14.917,
    longitude: 13.5,
    typology: 'T3',
    bedrooms: 3,
    bathrooms: 2,
    sqm: 180,
    parking: 2,
    pool: false,
    garden: true,
    energyCertificate: 'B',
    walkScore: 50,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80', alt: 'Fachada Lubango', isPrimary: true },
    ]),
    tags: JSON.stringify(['Serra da Chela', 'Família', 'Jardim']),
    propertyType: 'moradia-independente',
    condition: 'bom-estado',
  },
  {
    title: 'Arrendamento T4 na Maianga',
    description: 'Apartamento espaçoso em zona central de Luanda. Cozinha equipada, ar condicionado em todas as divisões, estacionamento privado.',
    price: 450000,
    currency: 'AOA',
    address: 'Avenida Combatentes da Liberdade, Edifício Maianga Center',
    city: 'Luanda',
    country: 'AO',
    neighborhood: 'Maianga',
    latitude: -8.82,
    longitude: 13.23,
    typology: 'T4',
    bedrooms: 4,
    bathrooms: 3,
    sqm: 220,
    parking: 1,
    pool: false,
    garden: false,
    energyCertificate: 'C',
    walkScore: 82,
    listingType: 'rent',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=800&q=80', alt: 'Sala ampla', isPrimary: true },
    ]),
    tags: JSON.stringify(['Central', 'Ar Condicionado', 'Mobilado']),
    propertyType: 'apartamento',
    condition: 'bom-estado',
  },
  {
    title: 'Terreno para Construção em Talatona',
    description: 'Lote de 1500m² em zona residencial de luxo. Projecto aprovado para moradia T6. Infraestruturas todas à porta.',
    price: 650000000,
    currency: 'AOA',
    address: 'Loteamento Jardins do Éden, Lote 23',
    city: 'Luanda',
    country: 'AO',
    neighborhood: 'Talatona',
    latitude: -8.91,
    longitude: 13.19,
    typology: 'Lote',
    bedrooms: 0,
    bathrooms: 0,
    sqm: 1500,
    parking: 0,
    pool: false,
    garden: false,
    energyCertificate: null,
    walkScore: 40,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80', alt: 'Vista terreno', isPrimary: true },
    ]),
    tags: JSON.stringify(['Lote', 'Projecto Aprovado', 'Investimento']),
    propertyType: 'terreno',
    condition: null,
  },
  {
    title: 'Duplex T3 no Benfica',
    description: 'Apartamento duplex com terraço panorâmico. Suite master com closet, escritório, cozinha gourmet. Condomínio com ginásio e piscina.',
    price: 1200000000,
    currency: 'AOA',
    address: 'Rua dos Kwanzas, Condomínio Horizonte',
    city: 'Luanda',
    country: 'AO',
    neighborhood: 'Benfica',
    latitude: -8.85,
    longitude: 13.22,
    typology: 'T3',
    bedrooms: 3,
    bathrooms: 3,
    sqm: 260,
    parking: 2,
    pool: true,
    garden: false,
    energyCertificate: 'A',
    walkScore: 72,
    listingType: 'sale',
    images: JSON.stringify([
      { url: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=800&q=80', alt: 'Sala duplex', isPrimary: true },
    ]),
    tags: JSON.stringify(['Duplex', 'Terraço', 'Ginásio']),
    propertyType: 'duplex',
    condition: 'nova',
  },
];

export const seedAggregatedListings = [
  {
    title: 'T3 Avenida da República, Lisboa',
    price: 39500000,
    currency: 'EUR',
    city: 'Lisboa',
    country: 'PT',
    neighborhood: 'Avenidas Novas',
    typology: 'T3',
    sqm: 95,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80',
    sourceUrl: 'https://www.idealista.pt/imovel/12345',
    sourcePortal: 'idealista',
    externalId: 'idealista-12345',
  },
  {
    title: 'T2 Rua de São Bento, Lisboa',
    price: 32000000,
    currency: 'EUR',
    city: 'Lisboa',
    country: 'PT',
    neighborhood: 'Estrela',
    typology: 'T2',
    sqm: 78,
    bedrooms: 2,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&q=80',
    sourceUrl: 'https://www.imovirtual.com/anuncio/t2-sao-bento',
    sourcePortal: 'imovirtual',
    externalId: 'imovirtual-67890',
  },
  {
    title: 'T4 Moradia, Porto',
    price: 75000000,
    currency: 'EUR',
    city: 'Porto',
    country: 'PT',
    neighborhood: 'Foz do Douro',
    typology: 'T4',
    sqm: 230,
    bedrooms: 4,
    bathrooms: 3,
    imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&q=80',
    sourceUrl: 'https://www.casasapo.pt/moradia-foz',
    sourcePortal: 'casasapo',
    externalId: 'casasapo-11111',
  },
  {
    title: 'T3 Apartamento, Cascais',
    price: 48500000,
    currency: 'EUR',
    city: 'Cascais',
    country: 'PT',
    neighborhood: 'Estoril',
    typology: 'T3',
    sqm: 120,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=400&q=80',
    sourceUrl: 'https://www.supercasa.pt/t3-estoril',
    sourcePortal: 'supercasa',
    externalId: 'supercasa-22222',
  },
  {
    title: 'T2 Avenida Combatentes, Luanda',
    price: 950000000,
    currency: 'AOA',
    city: 'Luanda',
    country: 'AO',
    neighborhood: 'Maianga',
    typology: 'T2',
    sqm: 100,
    bedrooms: 2,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=400&q=80',
    sourceUrl: 'https://www.olx.ao/anuncio/t2-maianga',
    sourcePortal: 'olx',
    externalId: 'olx-33333',
  },
];
